import type { JoinRequest } from '~/types/request'

/** Placeholder inbox rows for client demos / when Supabase is offline. */
export function createDemoRequests(): JoinRequest[] {
  const ago = (hours: number) =>
    new Date(Date.now() - hours * 60 * 60 * 1000).toISOString()

  return [
    {
      id: 1,
      ticket_code: 'LV-DEMO01',
      first_name: 'Sofia',
      surname: 'Marchetti',
      email: 'sofia.marchetti@example.com',
      phone: '082 555 0101',
      age: 29,
      note: 'Friend of the host — arriving with Marco.',
      status: 'PENDING',
      created_at: ago(2),
      decided_at: null,
    },
    {
      id: 2,
      ticket_code: 'LV-DEMO02',
      first_name: 'James',
      surname: 'Whitfield',
      email: 'j.whitfield@example.com',
      phone: '082 555 0102',
      age: 34,
      note: 'Vegetarian if catering — otherwise thrilled to be invited.',
      status: 'PENDING',
      created_at: ago(5),
      decided_at: null,
    },
    {
      id: 3,
      ticket_code: 'LV-DEMO03',
      first_name: 'Amara',
      surname: 'Okonkwo',
      email: 'amara.o@example.com',
      phone: '082 555 0103',
      age: 27,
      note: null,
      status: 'PENDING',
      created_at: ago(9),
      decided_at: null,
    },
    {
      id: 4,
      ticket_code: 'LV-DEMO04',
      first_name: 'Luca',
      surname: 'Bernardi',
      email: 'luca.bernardi@example.com',
      phone: '082 555 0104',
      age: 31,
      note: 'Can I bring a +1? Happy to keep it intimate if not.',
      status: 'PENDING',
      created_at: ago(14),
      decided_at: null,
    },
    {
      id: 5,
      ticket_code: 'LV-DEMO05',
      first_name: 'Elena',
      surname: 'Vasquez',
      email: 'elena.v@example.com',
      phone: '082 555 0105',
      age: 26,
      note: 'Poolside sunset sounds perfect.',
      status: 'APPROVED',
      created_at: ago(28),
      decided_at: ago(20),
    },
    {
      id: 6,
      ticket_code: 'LV-DEMO06',
      first_name: 'Tomás',
      surname: 'Herrera',
      email: 'tomas.h@example.com',
      phone: '082 555 0106',
      age: 33,
      note: 'Referred by Dani — thank you for considering me.',
      status: 'APPROVED',
      created_at: ago(36),
      decided_at: ago(24),
    },
    {
      id: 7,
      ticket_code: 'LV-DEMO07',
      first_name: 'Priya',
      surname: 'Shah',
      email: 'priya.shah@example.com',
      phone: '082 555 0107',
      age: 30,
      note: null,
      status: 'APPROVED',
      created_at: ago(48),
      decided_at: ago(30),
    },
    {
      id: 8,
      ticket_code: 'LV-DEMO08',
      first_name: 'Unknown',
      surname: 'Guest',
      email: 'plusone.random@example.com',
      phone: '082 555 0108',
      age: 24,
      note: 'Heard about the party online.',
      status: 'REJECTED',
      created_at: ago(52),
      decided_at: ago(40),
    },
    {
      id: 9,
      ticket_code: 'LV-DEMO09',
      first_name: 'Chris',
      surname: 'Dalton',
      email: 'c.dalton@example.com',
      phone: '082 555 0109',
      age: 38,
      note: 'Wrong weekend — asked to defer to next event.',
      status: 'REJECTED',
      created_at: ago(72),
      decided_at: ago(60),
    },
  ]
}
